name: build-checks

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java for Flutter
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Lint
        run: |
          cd formente
          flutter pub get
          flutter analyze
  build-apk:
    needs: lint-check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java for Flutter
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Install dependencies
        run: |
          cd formente
          flutter pub get
      - name: Build APK
        run: |
          cd formente
          flutter build apk --no-sound-null-safety
